source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'APMRatingControl_Example', :exclusive => true do
  pod "APMRatingControl", :path => "../"
end

target 'APMRatingControl_Tests', :exclusive => true do
  pod "APMRatingControl", :path => "../"

  
end
