source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!


abstract_target 'APMRatingControl' do
  pod "APMRatingControl", :path => "../"

  target 'APMRatingControl_Example'
  target 'APMRatingControl_Tests'
end
